###########################################

Title="v.out.ogr test" 

Description="Basic function test of v.out.ogr, only ESRI shape and MapInfo files are generated" 

NEED_OGR="yes"

NumberOfTests=8
  
TMPDIR=$TMP_DATA_DIR

i=0
while [ ${i} -lt ${NumberOfTests} ] ; do
  Module[${i}]="v.out.ogr"
  basename[${i}]="OGRExportData_${i}" 
  ModuleOutputType[${i}]="file" 
  let  i=${i}+1
done

# The output files generated by v.out.ogr. The md5 checksums must be in the same order as those output files
# But it is allowed to skip the last md5 checksums e.g.: the .map file of MapInfo output is not validated
ModuleOutput[0]="${TMPDIR}/${basename[0]}.dbf ${TMPDIR}/${basename[0]}.prj ${TMPDIR}/${basename[0]}.shp ${TMPDIR}/${basename[0]}.shx" 
ModuleOutput[1]="${TMPDIR}/${basename[1]}.dat ${TMPDIR}/${basename[1]}.id  ${TMPDIR}/${basename[1]}.tab ${TMPDIR}/${basename[1]}.map" 
ModuleOutput[2]="${TMPDIR}/${basename[2]}.dbf ${TMPDIR}/${basename[2]}.prj ${TMPDIR}/${basename[2]}.shp ${TMPDIR}/${basename[2]}.shx" 
ModuleOutput[3]="${TMPDIR}/${basename[3]}.dat ${TMPDIR}/${basename[3]}.id  ${TMPDIR}/${basename[3]}.tab ${TMPDIR}/${basename[3]}.map" 
ModuleOutput[4]="${TMPDIR}/${basename[4]}.dbf ${TMPDIR}/${basename[4]}.prj ${TMPDIR}/${basename[4]}.shp ${TMPDIR}/${basename[4]}.shx" 
ModuleOutput[5]="${TMPDIR}/${basename[5]}.dat ${TMPDIR}/${basename[5]}.id  ${TMPDIR}/${basename[5]}.tab ${TMPDIR}/${basename[5]}.map" 
ModuleOutput[6]="${TMPDIR}/${basename[6]}.dbf ${TMPDIR}/${basename[6]}.prj ${TMPDIR}/${basename[6]}.shp ${TMPDIR}/${basename[6]}.shx" 
ModuleOutput[7]="${TMPDIR}/${basename[7]}.dat ${TMPDIR}/${basename[7]}.id  ${TMPDIR}/${basename[7]}.tab ${TMPDIR}/${basename[7]}.map" 
  

# The  .map file of MapInfo output is not validated, only 3 entries are made for the MapInfo md5 checksums
ModuleValidationMD5[0]="
9f0f991d47819f3e7f63c0e51217f3c8 72286d2c95b63642d32066aab6c57959
9ddc0e3214b02ede936ffeb5fb52a1e0 10b5ce69ba70f3368b00198f7a12d744
" 
ModuleValidationMD5[1]="
1eccf372a4b9136798a87d35c491fd70 78d8917df014028b514e931465f1f1e9 
0c38b9bdfa13033bc57f52d6ae1b7475" #only .dat, .id and .tab are tested, the .map file is ignored 
ModuleValidationMD5[2]="
f31f1e54d6a9d5ee4c5816a6315fd1b7 72286d2c95b63642d32066aab6c57959
b0e942f2866de75caa66eb8872b3fe04 b29adb2b67c6f324db9640c7c0b90e19" 
ModuleValidationMD5[3]="
40c557df523ee87f8e21155e5f8176e0 423c7a25c7f604f14012ffc555db135c 
0c38b9bdfa13033bc57f52d6ae1b7475" #only .dat, .id and .tab are tested, the .map file is ignored
ModuleValidationMD5[4]="
e9b974ae6166a7d713aa924692c417d9 72286d2c95b63642d32066aab6c57959
2b02553b3234aa3ba80a49a36884aa27 4314809a665c7bc0189045839632c5f3" 
ModuleValidationMD5[5]="
75886da7255f0fe80569e280753e852e 36729e0a799464d81605834573b1964c 
0c38b9bdfa13033bc57f52d6ae1b7475" #only .dat, .id and .tab are tested, the .map file is ignored
ModuleValidationMD5[6]="
851942b61dd9856cfba97a20a17c4ae7 72286d2c95b63642d32066aab6c57959
c59848ed83e9d1ac6ee05ff6eee946d5 2861b2ffd1442311c2e065b62e652ec7" 
ModuleValidationMD5[7]="
1463c6097883afbeee150c5af1ea8c73 64966524e0195312413c0a88310ff3f7 
0c38b9bdfa13033bc57f52d6ae1b7475" #only .dat, .id and .tab are tested, the .map file is ignored

ModuleOptions[0]="input=points format=ESRI_Shapefile type=point dsn=${TMPDIR} olayer=${basename[0]}"
ModuleOptions[1]="input=points format=MapInfo_File type=point dsn=${TMPDIR} olayer=${basename[1]}"
ModuleOptions[2]="input=lines format=ESRI_Shapefile  type=line dsn=${TMPDIR} olayer=${basename[2]}"
ModuleOptions[3]="input=lines format=MapInfo_File  type=line dsn=${TMPDIR} olayer=${basename[3]}"
ModuleOptions[4]="input=elevation format=ESRI_Shapefile type=line dsn=${TMPDIR} olayer=${basename[4]}"
ModuleOptions[5]="input=elevation format=MapInfo_File type=line dsn=${TMPDIR} olayer=${basename[5]}"
ModuleOptions[6]="input=areas format=ESRI_Shapefile type=centroid,boundary,area dsn=${TMPDIR} olayer=${basename[6]}"
ModuleOptions[7]="input=areas format=MapInfo_File type=area dsn=${TMPDIR} olayer=${basename[7]}"
